name: ci

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/new-grades-notifier:latest,ghcr.io/${{ github.repository_owner }}/new-grades-notifier:${{ github.sha }}
          build-args: |
            MONGO_URL=mongodb://mongo:27017/pronote
            RUN_EVERY=1
            NTFY_AUTH=${{ secrets.NTFY_AUTH }}
            PASSWORD=${{ secrets.PASSWORD }}
            USERNAME=${{ secrets.USERNAME }}
